// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wprawka_1.Data;

#nullable disable

namespace Wprawka_1.Migrations
{
    [DbContext(typeof(VoltShareContext))]
    [Migration("20260328165140_RenameClusterNameColumn")]
    partial class RenameClusterNameColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserClusterMemberships", b =>
                {
                    b.Property<int>("ClustersId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ClustersId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserClusterMemberships");

                    b.HasData(
                        new
                        {
                            ClustersId = 1,
                            UsersId = 1
                        },
                        new
                        {
                            ClustersId = 2,
                            UsersId = 1
                        },
                        new
                        {
                            ClustersId = 2,
                            UsersId = 2
                        });
                });

            modelBuilder.Entity("Wprawka_1.Models.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Clusters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Klaster Północ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Klaster Południe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Klaster Wschód"
                        });
                });

            modelBuilder.Entity("Wprawka_1.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Homes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul. Wiejska 45, Białystok",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul. Mazowiecka 10, Warszawa",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "ul. Lipowa 1, Białystok",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Wprawka_1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan@wprawka.pl",
                            FullName = "Jan Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anna@nowak.pl",
                            FullName = "Anna Nowak"
                        });
                });

            modelBuilder.Entity("UserClusterMemberships", b =>
                {
                    b.HasOne("Wprawka_1.Models.Cluster", null)
                        .WithMany()
                        .HasForeignKey("ClustersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wprawka_1.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wprawka_1.Models.Home", b =>
                {
                    b.HasOne("Wprawka_1.Models.User", "User")
                        .WithMany("Homes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wprawka_1.Models.User", b =>
                {
                    b.Navigation("Homes");
                });
#pragma warning restore 612, 618
        }
    }
}
